import {
  AlignCenter,
  AlignLeft,
  AlignRight,
  AlignVerticalJustifyCenter,
  AlignVerticalJustifyEnd,
  AlignVerticalJustifyStart,
  AreaChart,
  ArrowDown01,
  ArrowDownToLine,
  ArrowUp10,
  ArrowUpToLine,
  BarChart3,
  BarChartHorizontal,
  Box,
  Calculator,
  Calendar,
  ChartCandlestick,
  ChartNoAxesCombined,
  Check,
  ChevronDown,
  ChevronRight,
  Circle,
  Code,
  Copy,
  Database,
  EllipsisVertical,
  FileChartColumnIncreasing,
  FunnelX,
  Gauge,
  GitCommitHorizontal,
  GripVertical,
  Hash,
  Layers2,
  LineChart,
  Loader,
  Palette,
  Pencil,
  PieChart,
  Plus,
  Radar,
  Redo2,
  RefreshCw,
  Save,
  ScatterChart,
  Search,
  Settings,
  Sigma,
  Table,
  ToggleLeft,
  Trash2,
  Type,
  Undo2,
  X,
} from 'lucide-react'

export const Icons = {
  add: Plus,
  alignCenter: AlignCenter,
  alignLeft: AlignLeft,
  alignRight: AlignRight,
  calculatedFieldAdd: Calculator,
  chartArea: AreaChart,
  chartBar: BarChart3,
  chartBoxplot: ChartCandlestick,
  chartCalendar: Calendar,
  chartCombo: ChartNoAxesCombined,
  chartFunnel: FunnelX,
  chartGauge: Gauge,
  chartHeatmap: Table,
  chartLine: LineChart,
  chartPie: PieChart,
  chartRadar: Radar,
  chartSankey: Layers2,
  chartScatter: ScatterChart,
  chartTreemap: Box,
  check: Check,
  chevronDown: ChevronDown,
  chevronRight: ChevronRight,
  close: X,
  code: Code,
  copy: Copy,
  delete: Trash2,
  Dimensions: Type,
  download: ArrowDownToLine,
  dragHandle: GripVertical,
  edit: Pencil,
  error: FunnelX,
  featureboolean: ToggleLeft,
  featuredate: Calendar,
  featurenumerical: Hash,
  featurestring: Type,
  filterClear: FunnelX,
  labelBottom: AlignVerticalJustifyStart,
  labelInside: AlignVerticalJustifyCenter,
  labelTop: AlignVerticalJustifyEnd,
  loading: Loader,
  Measures: Sigma,
  menu: EllipsisVertical,
  orientationHorizontal: BarChartHorizontal,
  orientationVertical: BarChart3,
  pointToggle: GitCommitHorizontal,
  radioIndicator: Circle,
  redo: Redo2,
  refresh: RefreshCw,
  report: FileChartColumnIncreasing,
  reportsettings: Settings,
  reportstyles: Palette,
  save: Save,
  search: Search,
  settings: Settings,
  sortAsc: ArrowUp10,
  sortDesc: ArrowDown01,
  stack: Layers2,
  tab: Database,
  tabadd: Plus,
  undo: Undo2,
  upload: ArrowUpToLine,
}
