import { Icons } from '@/config/icons'
import { commonAxisOptions } from './commonAxis'
import { commonLabelOptions } from './commonLabel'
import { commonLegendOptions } from './commonLegend'
import { commonNumberFormatOptions } from './commonNumberFormat'
import { commonTooltipOptions } from './commonTooltip'
import type { ChartConfig } from './types'

export const areaChartConfig: ChartConfig = {
  type: 'area',
  nameKey: 'charts.area.name',
  icon: Icons.chartArea,
  category: 'basic',
  descriptionKey: 'charts.area.description',
  supportsOrientation: false,
  supportsStacking: true,
  channels: [
    {
      id: 'x',
      labelKey: 'channels.columns',
      placeholderKey: 'channels.xAxis.placeholder',
      accepts: 'dimension',
      cardinality: 'single',
      required: true,
      icon: Icons.Dimensions,
      order: 1,
      tab: 'config',
      group: 'axes',
    },
    {
      id: 'y',
      labelKey: 'channels.rows',
      placeholderKey: 'channels.yAxis.placeholder',
      accepts: 'measure',
      cardinality: 'multiple',
      required: true,
      defaultAggregation: 'sum',
      icon: Icons.Measures,
      order: 2,
      tab: 'config',
      group: 'axes',
    },
    {
      id: 'color',
      labelKey: 'channels.breakdown',
      placeholderKey: 'channels.breakdownPlaceholder',
      accepts: 'dimension',
      cardinality: 'optional',
      required: false,
      icon: Icons.Dimensions,
      order: 3,
      tab: 'config',
      group: 'breakdown',
    },
  ],
  styleOptions: [
    {
      id: 'stackMode',
      labelKey: 'style.stackMode',
      type: 'toggle',
      defaultValue: false,
      tab: 'style',
      group: 'layout',
      order: 1,
    },
    {
      id: 'opacity',
      labelKey: 'style.opacity',
      type: 'slider',
      defaultValue: 0.4,
      min: 0.1,
      max: 1,
      step: 0.1,
      tab: 'style',
      group: 'appearance',
      order: 2,
    },
    {
      id: 'smooth',
      labelKey: 'style.smooth',
      type: 'toggle',
      defaultValue: false,
      tab: 'style',
      group: 'appearance',
      order: 3,
    },
    {
      id: 'showLine',
      labelKey: 'style.showLine',
      type: 'toggle',
      defaultValue: true,
      tab: 'style',
      group: 'appearance',
      order: 4,
    },
    {
      id: 'showPoints',
      labelKey: 'style.showPoints',
      type: 'toggle',
      defaultValue: true,
      tab: 'style',
      group: 'labels',
      order: 5,
    },
    ...commonLabelOptions,
    {
      id: 'showGrid',
      labelKey: 'style.showGrid',
      type: 'toggle',
      defaultValue: true,
      tab: 'style',
      group: 'grid',
      order: 5,
    },
    {
      id: 'gridLineWidth',
      labelKey: 'style.gridLineWidth',
      type: 'slider',
      defaultValue: 1,
      min: 0,
      max: 5,
      step: 1,
      tab: 'style',
      group: 'grid',
      order: 6,
    },
    {
      id: 'gridLineColor',
      labelKey: 'style.gridLineColor',
      type: 'color',
      defaultValue: 'hsl(var(--border))',
      tab: 'style',
      group: 'grid',
      order: 7,
    },
    ...commonLegendOptions,
    ...commonAxisOptions,
    ...commonTooltipOptions,
    ...commonNumberFormatOptions,
    {
      id: 'paletteName',
      labelKey: 'style.palette',
      type: 'select',
      defaultValue: 'zinc',
      options: [
        { value: 'zinc', labelKey: 'style.paletteZinc' },
        { value: 'slate', labelKey: 'style.paletteSlate' },
        { value: 'tableau10', labelKey: 'style.paletteTableau10' },
        { value: 'vibrant', labelKey: 'style.paletteVibrant' },
        { value: 'pastel', labelKey: 'style.palettePastel' },
      ],
      tab: 'style',
      group: 'colors',
      order: 12,
    },
  ],
  minRequirements: {
    dimensions: 1,
    measures: 1,
  },
}
