import { Icons } from '@/config/icons'
import { commonAxisOptions } from './commonAxis'
import { commonLabelOptions } from './commonLabel'
import { commonLegendOptions } from './commonLegend'
import { commonNumberFormatOptions } from './commonNumberFormat'
import { commonTooltipOptions } from './commonTooltip'
import type { ChartConfig } from './types'

export const barChartConfig: ChartConfig = {
  type: 'bar',
  nameKey: 'charts.bar.name',
  icon: Icons.chartBar,
  category: 'basic',
  descriptionKey: 'charts.bar.description',
  supportsOrientation: true,
  supportsStacking: true,
  channels: [
    {
      id: 'x',
      labelKey: 'channels.columns',
      placeholderKey: 'channels.xAxis.placeholder',
      accepts: 'dimension',
      cardinality: 'multiple',
      required: true,
      descriptionKey: 'channels.xAxis.description',
      icon: Icons.Dimensions,
      order: 1,
      tab: 'config',
      group: 'axes',
    },
    {
      id: 'y',
      labelKey: 'channels.rows',
      placeholderKey: 'channels.yAxis.placeholder',
      accepts: 'measure',
      cardinality: 'multiple',
      required: true,
      defaultAggregation: 'sum',
      descriptionKey: 'channels.yAxis.description',
      icon: Icons.Measures,
      order: 2,
      tab: 'config',
      group: 'axes',
    },
    {
      id: 'color',
      labelKey: 'channels.breakdown',
      placeholderKey: 'channels.breakdownPlaceholder',
      accepts: 'dimension',
      cardinality: 'optional',
      required: false,
      descriptionKey: 'channels.color.description',
      icon: Icons.Dimensions,
      order: 3,
      tab: 'config',
      group: 'breakdown',
    },
    {
      id: 'detail',
      labelKey: 'channels.detail',
      placeholderKey: 'channels.detailPlaceholder',
      accepts: 'dimension',
      cardinality: 'optional',
      required: false,
      descriptionKey: 'channels.detailDescription',
      icon: Icons.Dimensions,
      order: 4,
      tab: 'config',
      group: 'breakdown',
    },
  ],
  styleOptions: [
    {
      id: 'stackMode',
      labelKey: 'style.stackMode',
      type: 'toggle',
      defaultValue: false,
      tab: 'style',
      group: 'layout',
      order: 1,
    },
    {
      id: 'orientation',
      labelKey: 'style.orientation',
      type: 'toggle-group',
      defaultValue: 'vertical',
      options: [
        { value: 'vertical', labelKey: 'style.orientationVertical' },
        { value: 'horizontal', labelKey: 'style.orientationHorizontal' },
      ],
      tab: 'style',
      group: 'layout',
      order: 2,
    },
    {
      id: 'sortOrder',
      labelKey: 'style.sortOrder',
      type: 'select',
      defaultValue: 'none',
      options: [
        { value: 'none', labelKey: 'style.sortOrderNone' },
        { value: 'ascending', labelKey: 'style.sortOrderAscending' },
        { value: 'descending', labelKey: 'style.sortOrderDescending' },
      ],
      tab: 'style',
      group: 'layout',
      order: 3,
    },
    {
      id: 'barWidth',
      labelKey: 'style.barWidth',
      type: 'slider',
      defaultValue: 60,
      min: 20,
      max: 100,
      step: 5,
      tab: 'style',
      group: 'appearance',
      order: 3,
    },
    {
      id: 'borderRadius',
      labelKey: 'style.borderRadius',
      type: 'slider',
      defaultValue: 4,
      min: 0,
      max: 20,
      step: 1,
      tab: 'style',
      group: 'appearance',
      order: 4,
    },
    {
      id: 'barOpacity',
      labelKey: 'style.opacity',
      type: 'slider',
      defaultValue: 1,
      min: 0.1,
      max: 1,
      step: 0.1,
      tab: 'style',
      group: 'appearance',
      order: 5,
    },
    {
      id: 'barBorderWidth',
      labelKey: 'style.borderWidth',
      type: 'slider',
      defaultValue: 0,
      min: 0,
      max: 6,
      step: 1,
      tab: 'style',
      group: 'appearance',
      order: 6,
    },
    {
      id: 'barBorderColor',
      labelKey: 'style.borderColor',
      type: 'color',
      defaultValue: 'hsl(var(--border))',
      tab: 'style',
      group: 'appearance',
      order: 7,
    },
    ...commonLabelOptions,
    {
      id: 'showGrid',
      labelKey: 'style.showGrid',
      type: 'toggle',
      defaultValue: true,
      tab: 'style',
      group: 'grid',
      order: 6,
    },
    {
      id: 'gridLineWidth',
      labelKey: 'style.gridLineWidth',
      type: 'slider',
      defaultValue: 1,
      min: 0,
      max: 5,
      step: 1,
      tab: 'style',
      group: 'grid',
      order: 8,
    },
    {
      id: 'gridLineColor',
      labelKey: 'style.gridLineColor',
      type: 'color',
      defaultValue: 'hsl(var(--border))',
      tab: 'style',
      group: 'grid',
      order: 9,
    },
    ...commonLegendOptions,
    ...commonAxisOptions,
    ...commonTooltipOptions,
    ...commonNumberFormatOptions,
    {
      id: 'paletteName',
      labelKey: 'style.palette',
      type: 'select',
      defaultValue: 'zinc',
      options: [
        { value: 'zinc', labelKey: 'style.paletteZinc' },
        { value: 'slate', labelKey: 'style.paletteSlate' },
        { value: 'tableau10', labelKey: 'style.paletteTableau10' },
        { value: 'vibrant', labelKey: 'style.paletteVibrant' },
        { value: 'pastel', labelKey: 'style.palettePastel' },
      ],
      tab: 'style',
      group: 'colors',
      order: 16,
    },
  ],
  minRequirements: {
    dimensions: 1,
    measures: 1,
  },
}
