import { Icons } from '@/config/icons'
import { commonAxisOptions } from './commonAxis'
import { commonNumberFormatOptions } from './commonNumberFormat'
import { commonTooltipOptions } from './commonTooltip'
import type { ChartConfig } from './types'

export const boxplotChartConfig: ChartConfig = {
  type: 'boxplot',
  nameKey: 'charts.boxplot.name',
  icon: Icons.chartBoxplot,
  category: 'distribution',
  descriptionKey: 'charts.boxplot.description',
  supportsOrientation: true,
  supportsStacking: false,
  channels: [
    {
      id: 'category',
      labelKey: 'channels.category',
      placeholderKey: 'channels.categoryPlaceholder',
      accepts: 'dimension',
      cardinality: 'single',
      required: true,
      icon: Icons.Dimensions,
      order: 1,
      tab: 'config',
      group: 'axes',
    },
    {
      id: 'value',
      labelKey: 'channels.value',
      placeholderKey: 'channels.valueBoxplotPlaceholder',
      accepts: 'measure',
      cardinality: 'single',
      required: true,
      allowAggregation: false,
      icon: Icons.Measures,
      order: 2,
      tab: 'config',
      group: 'data',
    },
  ],
  styleOptions: [
    {
      id: 'orientation',
      labelKey: 'style.orientation',
      type: 'toggle-group',
      defaultValue: 'vertical',
      options: [
        { value: 'vertical', labelKey: 'style.orientationVertical' },
        { value: 'horizontal', labelKey: 'style.orientationHorizontal' },
      ],
      tab: 'style',
      group: 'layout',
      order: 1,
    },
    {
      id: 'boxWidth',
      labelKey: 'style.boxWidth',
      type: 'slider',
      defaultValue: 50,
      min: 20,
      max: 80,
      step: 5,
      tab: 'style',
      group: 'appearance',
      order: 2,
    },
    {
      id: 'boxColor',
      labelKey: 'style.boxColor',
      type: 'color',
      defaultValue: 'hsl(var(--primary))',
      tab: 'style',
      group: 'appearance',
      order: 3,
    },
    {
      id: 'boxBorderWidth',
      labelKey: 'style.borderWidth',
      type: 'slider',
      defaultValue: 1,
      min: 0,
      max: 6,
      step: 1,
      tab: 'style',
      group: 'appearance',
      order: 4,
    },
    {
      id: 'boxBorderColor',
      labelKey: 'style.boxBorderColor',
      type: 'color',
      defaultValue: 'hsl(var(--foreground))',
      tab: 'style',
      group: 'appearance',
      order: 5,
    },
    {
      id: 'showOutliers',
      labelKey: 'style.showOutliers',
      type: 'toggle',
      defaultValue: true,
      tab: 'style',
      group: 'appearance',
      order: 6,
    },
    {
      id: 'outlierColor',
      labelKey: 'style.outlierColor',
      type: 'color',
      defaultValue: 'hsl(var(--destructive))',
      tab: 'style',
      group: 'appearance',
      order: 7,
    },
    {
      id: 'showGrid',
      labelKey: 'style.showGrid',
      type: 'toggle',
      defaultValue: true,
      tab: 'style',
      group: 'grid',
      order: 8,
    },
    {
      id: 'gridLineWidth',
      labelKey: 'style.gridLineWidth',
      type: 'slider',
      defaultValue: 1,
      min: 0,
      max: 5,
      step: 1,
      tab: 'style',
      group: 'grid',
      order: 9,
    },
    {
      id: 'gridLineColor',
      labelKey: 'style.gridLineColor',
      type: 'color',
      defaultValue: 'hsl(var(--border))',
      tab: 'style',
      group: 'grid',
      order: 10,
    },
    ...commonAxisOptions,
    ...commonTooltipOptions,
    ...commonNumberFormatOptions,
  ],
  minRequirements: {
    dimensions: 1,
    measures: 1,
  },
}
