import { Icons } from '@/config/icons'
import { commonAxisOptions } from './commonAxis'
import { commonLabelOptions } from './commonLabel'
import { commonLegendOptions } from './commonLegend'
import { commonNumberFormatOptions } from './commonNumberFormat'
import { commonTooltipOptions } from './commonTooltip'
import type { ChartConfig } from './types'

export const comboChartConfig: ChartConfig = {
  type: 'combo',
  nameKey: 'charts.combo.name',
  icon: Icons.chartCombo,
  category: 'basic',
  descriptionKey: 'charts.combo.description',
  supportsOrientation: true,
  supportsStacking: true,
  channels: [
    {
      id: 'x',
      labelKey: 'channels.columns',
      placeholderKey: 'channels.xAxis.placeholder',
      accepts: 'dimension',
      cardinality: 'single',
      required: true,
      icon: Icons.Dimensions,
      order: 1,
      tab: 'config',
      group: 'axes',
    },
    {
      id: 'bars',
      labelKey: 'channels.bars',
      placeholderKey: 'channels.barsPlaceholder',
      accepts: 'measure',
      cardinality: 'multiple',
      required: true,
      defaultAggregation: 'sum',
      icon: Icons.Measures,
      order: 2,
      tab: 'config',
      group: 'series',
    },
    {
      id: 'lines',
      labelKey: 'channels.lines',
      placeholderKey: 'channels.linesPlaceholder',
      accepts: 'measure',
      cardinality: 'single',
      required: false,
      defaultAggregation: 'avg',
      icon: Icons.Measures,
      order: 3,
      tab: 'config',
      group: 'series',
    },
  ],
  styleOptions: [
    {
      id: 'stackMode',
      labelKey: 'style.stackMode',
      type: 'toggle',
      defaultValue: false,
      tab: 'style',
      group: 'layout',
      order: 1,
    },
    {
      id: 'lineWidth',
      labelKey: 'style.lineWidth',
      type: 'slider',
      defaultValue: 2,
      min: 1,
      max: 6,
      step: 0.5,
      tab: 'style',
      group: 'appearance',
      order: 2,
    },
    {
      id: 'showPoints',
      labelKey: 'style.showPoints',
      type: 'toggle',
      defaultValue: true,
      tab: 'style',
      group: 'appearance',
      order: 3,
    },
    ...commonLabelOptions.map((option, idx) => ({
      ...option,
      group: 'appearance',
      order: 30 + idx,
    })),
    {
      id: 'barWidth',
      labelKey: 'style.barWidth',
      type: 'slider',
      defaultValue: 60,
      min: 20,
      max: 100,
      step: 5,
      tab: 'style',
      group: 'appearance',
      order: 4,
    },
    {
      id: 'borderRadius',
      labelKey: 'style.borderRadius',
      type: 'slider',
      defaultValue: 4,
      min: 0,
      max: 20,
      step: 1,
      tab: 'style',
      group: 'appearance',
      order: 5,
    },
    {
      id: 'barOpacity',
      labelKey: 'style.opacity',
      type: 'slider',
      defaultValue: 1,
      min: 0.1,
      max: 1,
      step: 0.1,
      tab: 'style',
      group: 'appearance',
      order: 6,
    },
    {
      id: 'barBorderWidth',
      labelKey: 'style.borderWidth',
      type: 'slider',
      defaultValue: 0,
      min: 0,
      max: 6,
      step: 1,
      tab: 'style',
      group: 'appearance',
      order: 7,
    },
    {
      id: 'barBorderColor',
      labelKey: 'style.borderColor',
      type: 'color',
      defaultValue: 'hsl(var(--border))',
      tab: 'style',
      group: 'appearance',
      order: 8,
    },
    {
      id: 'showGrid',
      labelKey: 'style.showGrid',
      type: 'toggle',
      defaultValue: true,
      tab: 'style',
      group: 'grid',
      order: 9,
    },
    {
      id: 'gridLineWidth',
      labelKey: 'style.gridLineWidth',
      type: 'slider',
      defaultValue: 1,
      min: 0,
      max: 5,
      step: 1,
      tab: 'style',
      group: 'grid',
      order: 10,
    },
    {
      id: 'gridLineColor',
      labelKey: 'style.gridLineColor',
      type: 'color',
      defaultValue: 'hsl(var(--border))',
      tab: 'style',
      group: 'grid',
      order: 11,
    },
    ...commonLegendOptions,
    ...commonAxisOptions,
    ...commonTooltipOptions,
    ...commonNumberFormatOptions,
  ],
  minRequirements: {
    dimensions: 1,
    measures: 1,
  },
}
