import type { StyleOptionDefinition } from './types'

export const commonTooltipOptions: StyleOptionDefinition[] = [
  {
    id: 'showTooltip',
    labelKey: 'style.showTooltip',
    type: 'toggle',
    defaultValue: true,
    tab: 'style',
    group: 'tooltip',
    order: 400,
  },
  {
    id: 'tooltipFontSize',
    labelKey: 'style.tooltipFontSize',
    type: 'slider',
    defaultValue: 12,
    min: 8,
    max: 24,
    step: 1,
    tab: 'style',
    group: 'tooltip',
    order: 401,
  },
  {
    id: 'tooltipBorderWidth',
    labelKey: 'style.tooltipBorderWidth',
    type: 'slider',
    defaultValue: 1,
    min: 0,
    max: 5,
    step: 1,
    tab: 'style',
    group: 'tooltip',
    order: 402,
  },
  {
    id: 'tooltipBorderColor',
    labelKey: 'style.tooltipBorderColor',
    type: 'color',
    defaultValue: 'hsl(var(--border))',
    tab: 'style',
    group: 'tooltip',
    order: 403,
  },
  {
    id: 'tooltipBackgroundColor',
    labelKey: 'style.tooltipBackgroundColor',
    type: 'color',
    defaultValue: 'hsl(var(--popover))',
    tab: 'style',
    group: 'tooltip',
    order: 404,
  },
  {
    id: 'tooltipBackgroundOpacity',
    labelKey: 'style.tooltipBackgroundOpacity',
    type: 'slider',
    defaultValue: 1,
    min: 0.1,
    max: 1,
    step: 0.05,
    tab: 'style',
    group: 'tooltip',
    order: 405,
  },
  {
    id: 'tooltipTextColor',
    labelKey: 'style.tooltipTextColor',
    type: 'color',
    defaultValue: 'hsl(var(--secondary-foreground))',
    tab: 'style',
    group: 'tooltip',
    order: 406,
  },
]
