import type { StyleOptionDefinition } from './types'

export const commonLegendOptions: StyleOptionDefinition[] = [
  {
    id: 'showLegend',
    labelKey: 'style.showLegend',
    type: 'toggle',
    defaultValue: true,
    tab: 'style',
    group: 'legend',
    order: 100,
  },
  {
    id: 'legendFontSize',
    labelKey: 'style.legendFontSize',
    type: 'slider',
    defaultValue: 12,
    min: 8,
    max: 24,
    step: 1,
    tab: 'style',
    group: 'legend',
    order: 101,
  },
  {
    id: 'legendColor',
    labelKey: 'style.legendColor',
    type: 'color',
    defaultValue: 'hsl(var(--foreground))',
    tab: 'style',
    group: 'legend',
    order: 102,
  },
  {
    id: 'legendBold',
    labelKey: 'style.legendBold',
    type: 'toggle',
    defaultValue: false,
    tab: 'style',
    group: 'legend',
    order: 103,
  },
  {
    id: 'legendItalic',
    labelKey: 'style.legendItalic',
    type: 'toggle',
    defaultValue: false,
    tab: 'style',
    group: 'legend',
    order: 104,
  },
  {
    id: 'legendUnderline',
    labelKey: 'style.legendUnderline',
    type: 'toggle',
    defaultValue: false,
    tab: 'style',
    group: 'legend',
    order: 105,
  },
  {
    id: 'legendAlign',
    labelKey: 'style.legendAlign',
    type: 'select', // Handled manually in LegendSection, type here is for fallback/schema
    defaultValue: 'center',
    options: [
      { value: 'left', labelKey: 'style.alignLeft' },
      { value: 'center', labelKey: 'style.alignCenter' },
      { value: 'right', labelKey: 'style.alignRight' },
    ],
    tab: 'style',
    group: 'legend',
    order: 106,
  },
]
