import type { StyleOptionDefinition } from './types'

export const commonAxisOptions: StyleOptionDefinition[] = [
  {
    id: 'showXAxis',
    labelKey: 'style.showXAxis',
    type: 'toggle',
    defaultValue: true,
    tab: 'style',
    group: 'axis',
    order: 300,
  },
  {
    id: 'xAxisFontSize',
    labelKey: 'style.axisFontSize',
    type: 'slider',
    defaultValue: 11,
    min: 8,
    max: 22,
    step: 1,
    tab: 'style',
    group: 'axis',
    order: 301,
  },
  {
    id: 'xAxisColor',
    labelKey: 'style.axisColor',
    type: 'color',
    defaultValue: 'hsl(var(--muted-foreground))',
    tab: 'style',
    group: 'axis',
    order: 302,
  },
  {
    id: 'xAxisBold',
    labelKey: 'style.axisBold',
    type: 'toggle',
    defaultValue: false,
    tab: 'style',
    group: 'axis',
    order: 303,
  },
  {
    id: 'xAxisItalic',
    labelKey: 'style.axisItalic',
    type: 'toggle',
    defaultValue: false,
    tab: 'style',
    group: 'axis',
    order: 304,
  },
  {
    id: 'xAxisUnderline',
    labelKey: 'style.axisUnderline',
    type: 'toggle',
    defaultValue: false,
    tab: 'style',
    group: 'axis',
    order: 305,
  },
  {
    id: 'xAxisLineWidth',
    labelKey: 'style.axisLineWidth',
    type: 'slider',
    defaultValue: 1,
    min: 1,
    max: 4,
    step: 1,
    tab: 'style',
    group: 'axis',
    order: 306,
  },
  {
    id: 'xAxisLineColor',
    labelKey: 'style.axisLineColor',
    type: 'color',
    defaultValue: 'hsl(var(--muted-foreground))',
    tab: 'style',
    group: 'axis',
    order: 307,
  },
  {
    id: 'showYAxis',
    labelKey: 'style.showYAxis',
    type: 'toggle',
    defaultValue: true,
    tab: 'style',
    group: 'axis',
    order: 308,
  },
  {
    id: 'yAxisFontSize',
    labelKey: 'style.axisFontSize',
    type: 'slider',
    defaultValue: 11,
    min: 8,
    max: 22,
    step: 1,
    tab: 'style',
    group: 'axis',
    order: 309,
  },
  {
    id: 'yAxisColor',
    labelKey: 'style.axisColor',
    type: 'color',
    defaultValue: 'hsl(var(--muted-foreground))',
    tab: 'style',
    group: 'axis',
    order: 310,
  },
  {
    id: 'yAxisBold',
    labelKey: 'style.axisBold',
    type: 'toggle',
    defaultValue: false,
    tab: 'style',
    group: 'axis',
    order: 311,
  },
  {
    id: 'yAxisItalic',
    labelKey: 'style.axisItalic',
    type: 'toggle',
    defaultValue: false,
    tab: 'style',
    group: 'axis',
    order: 312,
  },
  {
    id: 'yAxisUnderline',
    labelKey: 'style.axisUnderline',
    type: 'toggle',
    defaultValue: false,
    tab: 'style',
    group: 'axis',
    order: 313,
  },
  {
    id: 'yAxisLineWidth',
    labelKey: 'style.axisLineWidth',
    type: 'slider',
    defaultValue: 1,
    min: 1,
    max: 4,
    step: 1,
    tab: 'style',
    group: 'axis',
    order: 314,
  },
  {
    id: 'yAxisLineColor',
    labelKey: 'style.axisLineColor',
    type: 'color',
    defaultValue: 'hsl(var(--muted-foreground))',
    tab: 'style',
    group: 'axis',
    order: 315,
  },
]
