import { Icons } from '@/config/icons'
import { commonNumberFormatOptions } from './commonNumberFormat'
import { commonTooltipOptions } from './commonTooltip'
import type { ChartConfig } from './types'

export const funnelChartConfig: ChartConfig = {
  type: 'funnel',
  nameKey: 'charts.funnel.name',
  icon: Icons.chartFunnel,
  category: 'flow',
  descriptionKey: 'charts.funnel.description',
  supportsOrientation: true,
  supportsStacking: false,
  channels: [
    {
      id: 'stage',
      labelKey: 'channels.stage',
      placeholderKey: 'channels.stagePlaceholder',
      accepts: 'dimension',
      cardinality: 'single',
      required: true,
      icon: Icons.Dimensions,
      order: 1,
      tab: 'config',
      group: 'data',
    },
    {
      id: 'value',
      labelKey: 'channels.value',
      placeholderKey: 'channels.valuePlaceholder',
      accepts: 'measure',
      cardinality: 'single',
      required: true,
      defaultAggregation: 'sum',
      icon: Icons.Measures,
      order: 2,
      tab: 'config',
      group: 'data',
    },
  ],
  styleOptions: [
    {
      id: 'sortMode',
      labelKey: 'style.sortMode',
      type: 'toggle-group',
      defaultValue: 'descending',
      options: [
        { value: 'descending', labelKey: 'style.sortModeDescending' },
        { value: 'ascending', labelKey: 'style.sortModeAscending' },
      ],
      tab: 'style',
      group: 'layout',
      order: 1,
    },
    {
      id: 'showLabels',
      labelKey: 'style.showLabels',
      type: 'toggle',
      defaultValue: true,
      tab: 'style',
      group: 'labels',
      order: 2,
    },
    {
      id: 'percentageMode',
      labelKey: 'style.percentageMode',
      type: 'select',
      defaultValue: 'value_percentage',
      options: [
        { value: 'none', labelKey: 'style.displayMode.none' },
        { value: 'percentage', labelKey: 'style.displayMode.percentage' },
        {
          value: 'value_percentage',
          labelKey: 'style.displayMode.valuePercentage',
        },
      ],
      tab: 'style',
      group: 'labels',
      order: 3,
    },
    {
      id: 'labelPosition',
      labelKey: 'style.labelPosition',
      type: 'select',
      defaultValue: 'right',
      options: [
        { value: 'left', labelKey: 'style.positionLeft' },
        { value: 'inside', labelKey: 'style.positionInside' },
        { value: 'right', labelKey: 'style.positionRight' },
      ],
      tab: 'style',
      group: 'labels',
      order: 4,
    },
    {
      id: 'showLabelLine',
      labelKey: 'style.showLabelLine',
      type: 'toggle',
      defaultValue: true,
      tab: 'style',
      group: 'labels',
      order: 5,
    },
    {
      id: 'labelLineLength',
      labelKey: 'style.lineWidth',
      type: 'slider',
      defaultValue: 14,
      min: 0,
      max: 40,
      step: 1,
      tab: 'style',
      group: 'labels',
      order: 6,
    },
    {
      id: 'gap',
      labelKey: 'style.gap',
      type: 'slider',
      defaultValue: 2,
      min: 0,
      max: 10,
      step: 1,
      tab: 'style',
      group: 'appearance',
      order: 7,
    },
    {
      id: 'borderWidth',
      labelKey: 'style.borderWidth',
      type: 'slider',
      defaultValue: 1,
      min: 0,
      max: 6,
      step: 1,
      tab: 'style',
      group: 'appearance',
      order: 8,
    },
    {
      id: 'borderColor',
      labelKey: 'style.borderColor',
      type: 'color',
      defaultValue: 'hsl(var(--background))',
      tab: 'style',
      group: 'appearance',
      order: 9,
    },
    {
      id: 'showLegend',
      labelKey: 'style.showLegend',
      type: 'toggle',
      defaultValue: true,
      tab: 'style',
      group: 'legend',
      order: 10,
    },
    {
      id: 'legendFontSize',
      labelKey: 'style.legendFontSize',
      type: 'slider',
      defaultValue: 12,
      min: 8,
      max: 24,
      step: 1,
      tab: 'style',
      group: 'legend',
      order: 11,
    },
    {
      id: 'legendBold',
      labelKey: 'style.legendBold',
      type: 'toggle',
      defaultValue: false,
      tab: 'style',
      group: 'legend',
      order: 12,
    },
    {
      id: 'legendItalic',
      labelKey: 'style.legendItalic',
      type: 'toggle',
      defaultValue: false,
      tab: 'style',
      group: 'legend',
      order: 13,
    },
    {
      id: 'legendUnderline',
      labelKey: 'style.legendUnderline',
      type: 'toggle',
      defaultValue: false,
      tab: 'style',
      group: 'legend',
      order: 14,
    },
    {
      id: 'legendColor',
      labelKey: 'style.legendColor',
      type: 'color',
      defaultValue: 'hsl(var(--foreground))',
      tab: 'style',
      group: 'legend',
      order: 15,
    },
    ...commonTooltipOptions,
    ...commonNumberFormatOptions,
  ],
  minRequirements: {
    dimensions: 1,
    measures: 1,
  },
}
