import { Icons } from '@/config/icons'
import { commonLabelOptions } from './commonLabel'
import { commonNumberFormatOptions } from './commonNumberFormat'
import { commonTooltipOptions } from './commonTooltip'
import type { ChartConfig } from './types'

export const heatmapChartConfig: ChartConfig = {
  type: 'heatmap',
  nameKey: 'charts.heatmap.name',
  icon: Icons.chartHeatmap,
  category: 'relationship',
  descriptionKey: 'charts.heatmap.description',
  supportsOrientation: false,
  supportsStacking: false,
  channels: [
    {
      id: 'x',
      labelKey: 'channels.columns',
      placeholderKey: 'channels.xAxis.heatmapPlaceholder',
      accepts: 'dimension',
      cardinality: 'single',
      required: true,
      icon: Icons.Dimensions,
      order: 1,
      tab: 'config',
      group: 'axes',
    },
    {
      id: 'y',
      labelKey: 'channels.rows',
      placeholderKey: 'channels.yAxis.heatmapPlaceholder',
      accepts: 'dimension',
      cardinality: 'single',
      required: true,
      icon: Icons.Dimensions,
      order: 2,
      tab: 'config',
      group: 'axes',
    },
    {
      id: 'value',
      labelKey: 'channels.value',
      placeholderKey: 'channels.valueHeatmapPlaceholder',
      accepts: 'measure',
      cardinality: 'single',
      required: true,
      defaultAggregation: 'sum',
      icon: Icons.Measures,
      order: 3,
      tab: 'config',
      group: 'data',
    },
  ],
  styleOptions: [
    {
      id: 'colorScheme',
      labelKey: 'style.colorScheme',
      type: 'select',
      defaultValue: 'blues',
      options: [
        { value: 'blues', labelKey: 'style.colorSchemeBlues' },
        { value: 'greens', labelKey: 'style.colorSchemeGreens' },
        { value: 'reds', labelKey: 'style.colorSchemeReds' },
        { value: 'oranges', labelKey: 'style.colorSchemeOranges' },
        { value: 'purples', labelKey: 'style.colorSchemePurples' },
        { value: 'diverging', labelKey: 'style.colorSchemeDiverging' },
      ],
      tab: 'style',
      group: 'colors',
      order: 1,
    },
    ...commonLabelOptions,
    {
      id: 'percentageMode',
      labelKey: 'style.percentageMode',
      type: 'select',
      defaultValue: 'none',
      options: [
        { value: 'none', labelKey: 'style.displayMode.none' },
        { value: 'percentage', labelKey: 'style.displayMode.percentage' },
        {
          value: 'value_percentage',
          labelKey: 'style.displayMode.valuePercentage',
        },
      ],
      tab: 'style',
      group: 'labels',
      order: 10,
    },
    {
      id: 'showBorder',
      labelKey: 'style.showBorder',
      type: 'toggle',
      defaultValue: true,
      tab: 'style',
      group: 'grid',
      order: 11,
    },
    {
      id: 'cellBorderWidth',
      labelKey: 'style.cellBorderWidth',
      type: 'slider',
      defaultValue: 1,
      min: 0,
      max: 4,
      step: 0.5,
      tab: 'style',
      group: 'grid',
      order: 12,
    },
    {
      id: 'cellBorderColor',
      labelKey: 'style.borderColor',
      type: 'color',
      defaultValue: 'rgba(0,0,0,0.08)',
      tab: 'style',
      group: 'grid',
      order: 13,
    },
    {
      id: 'showLegend',
      labelKey: 'style.showLegend',
      type: 'toggle',
      defaultValue: true,
      tab: 'style',
      group: 'legend',
      order: 14,
    },
    {
      id: 'legendFontSize',
      labelKey: 'style.legendFontSize',
      type: 'slider',
      defaultValue: 12,
      min: 8,
      max: 24,
      step: 1,
      tab: 'style',
      group: 'legend',
      order: 15,
    },
    {
      id: 'legendAlign',
      labelKey: 'style.legendAlign',
      type: 'select',
      defaultValue: 'center',
      options: [
        { value: 'left', labelKey: 'style.alignLeft' },
        { value: 'center', labelKey: 'style.alignCenter' },
        { value: 'right', labelKey: 'style.alignRight' },
      ],
      tab: 'style',
      group: 'legend',
      order: 16,
    },
    {
      id: 'legendBold',
      labelKey: 'style.legendBold',
      type: 'toggle',
      defaultValue: false,
      tab: 'style',
      group: 'legend',
      order: 17,
    },
    {
      id: 'legendItalic',
      labelKey: 'style.legendItalic',
      type: 'toggle',
      defaultValue: false,
      tab: 'style',
      group: 'legend',
      order: 18,
    },
    {
      id: 'legendUnderline',
      labelKey: 'style.legendUnderline',
      type: 'toggle',
      defaultValue: false,
      tab: 'style',
      group: 'legend',
      order: 19,
    },
    ...commonTooltipOptions,
    ...commonNumberFormatOptions,
  ],
  minRequirements: {
    dimensions: 2,
    measures: 1,
  },
}
