import { Icons } from '@/config/icons'
import { commonLabelOptions } from './commonLabel'
import { commonLegendOptions } from './commonLegend'
import { commonNumberFormatOptions } from './commonNumberFormat'
import { commonTooltipOptions } from './commonTooltip'
import type { ChartConfig } from './types'

export const pieChartConfig: ChartConfig = {
  type: 'pie',
  nameKey: 'charts.pie.name',
  icon: Icons.chartPie,
  category: 'basic',
  descriptionKey: 'charts.pie.description',
  supportsOrientation: false,
  supportsStacking: false,
  channels: [
    {
      id: 'segment',
      labelKey: 'channels.segment',
      placeholderKey: 'channels.segmentPlaceholder',
      accepts: 'dimension',
      cardinality: 'single',
      required: true,
      descriptionKey: 'channels.segmentDescription',
      icon: Icons.Dimensions,
      order: 1,
      tab: 'config',
      group: 'data',
    },
    {
      id: 'value',
      labelKey: 'channels.value',
      placeholderKey: 'channels.valuePlaceholder',
      accepts: 'measure',
      cardinality: 'single',
      required: true,
      defaultAggregation: 'sum',
      descriptionKey: 'channels.valueDescription',
      icon: Icons.Measures,
      order: 2,
      tab: 'config',
      group: 'data',
    },
  ],
  styleOptions: [
    {
      id: 'sortOrder',
      labelKey: 'style.sortOrder',
      type: 'select',
      defaultValue: 'none',
      options: [
        { value: 'none', labelKey: 'style.sortOrderNone' },
        { value: 'ascending', labelKey: 'style.sortOrderAscending' },
        { value: 'descending', labelKey: 'style.sortOrderDescending' },
      ],
      tab: 'style',
      group: 'layout',
      order: 1,
    },
    {
      id: 'variant',
      labelKey: 'style.pieVariant',
      type: 'select',
      defaultValue: 'pie',
      options: [
        { value: 'pie', labelKey: 'style.pieVariantPie' },
        { value: 'donut', labelKey: 'style.pieVariantDonut' },
      ],
      tab: 'style',
      group: 'layout',
      order: 2,
    },
    {
      id: 'innerRadius',
      labelKey: 'style.innerRadius',
      type: 'slider',
      defaultValue: 50,
      min: 0,
      max: 80,
      step: 5,
      tab: 'style',
      group: 'layout',
      order: 3,
    },
    {
      id: 'startAngle',
      labelKey: 'style.startAngle',
      type: 'slider',
      defaultValue: 90,
      min: 0,
      max: 360,
      step: 15,
      tab: 'style',
      group: 'layout',
      order: 4,
    },
    ...commonLabelOptions,
    {
      id: 'percentageMode',
      labelKey: 'style.percentageMode',
      type: 'select',
      defaultValue: 'percentage',
      options: [
        { value: 'none', labelKey: 'style.displayMode.none' },
        { value: 'percentage', labelKey: 'style.displayMode.percentage' },
        {
          value: 'value_percentage',
          labelKey: 'style.displayMode.valuePercentage',
        },
      ],
      tab: 'style',
      group: 'labels',
      order: 4,
    },
    {
      id: 'showLabelLine',
      labelKey: 'style.showLabelLine',
      type: 'toggle',
      defaultValue: true,
      tab: 'style',
      group: 'labels',
      order: 5,
    },
    ...commonLegendOptions,
    ...commonTooltipOptions,
    ...commonNumberFormatOptions,
    {
      id: 'paletteName',
      labelKey: 'style.palette',
      type: 'select',
      defaultValue: 'zinc',
      options: [
        { value: 'zinc', labelKey: 'style.paletteZinc' },
        { value: 'slate', labelKey: 'style.paletteSlate' },
        { value: 'tableau10', labelKey: 'style.paletteTableau10' },
        { value: 'vibrant', labelKey: 'style.paletteVibrant' },
        { value: 'pastel', labelKey: 'style.palettePastel' },
      ],
      tab: 'style',
      group: 'colors',
      order: 12,
    },
  ],
  minRequirements: {
    dimensions: 1,
    measures: 1,
  },
}
