import { Icons } from '@/config/icons'
import { commonLegendOptions } from './commonLegend'
import { commonNumberFormatOptions } from './commonNumberFormat'
import { commonTooltipOptions } from './commonTooltip'
import type { ChartConfig } from './types'

export const radarChartConfig: ChartConfig = {
  type: 'radar',
  nameKey: 'charts.radar.name',
  icon: Icons.chartRadar,
  category: 'relationship',
  descriptionKey: 'charts.radar.description',
  supportsOrientation: false,
  supportsStacking: false,

  channels: [
    {
      id: 'series',
      labelKey: 'channels.breakdown',
      placeholderKey: 'channels.breakdownPlaceholder',
      accepts: 'dimension',
      cardinality: 'optional',
      required: false,
      icon: Icons.Dimensions,
      order: 1,
      tab: 'config',
      group: 'data',
    },
    {
      id: 'values',
      labelKey: 'channels.values',
      placeholderKey: 'channels.valuesPlaceholder',
      accepts: 'measure',
      cardinality: 'multiple',
      required: true,
      defaultAggregation: 'avg',
      icon: Icons.Measures,
      order: 2,
      tab: 'config',
      group: 'data',
    },
  ],

  styleOptions: [
    {
      id: 'shape',
      labelKey: 'style.radarShape',
      type: 'select',
      defaultValue: 'polygon',
      options: [
        { value: 'polygon', labelKey: 'style.radarShapePolygon' },
        { value: 'circle', labelKey: 'style.radarShapeCircle' },
      ],
      tab: 'style',
      group: 'layout',
      order: 1,
    },
    {
      id: 'lineWidth',
      labelKey: 'style.lineWidth',
      type: 'slider',
      defaultValue: 2,
      min: 1,
      max: 6,
      step: 0.5,
      tab: 'style',
      group: 'appearance',
      order: 2,
    },
    {
      id: 'showArea',
      labelKey: 'style.showArea',
      type: 'toggle',
      defaultValue: true,
      tab: 'style',
      group: 'appearance',
      order: 3,
    },
    {
      id: 'areaOpacity',
      labelKey: 'style.opacity',
      type: 'slider',
      defaultValue: 0.25,
      min: 0.05,
      max: 1,
      step: 0.05,
      tab: 'style',
      group: 'appearance',
      order: 4,
    },
    {
      id: 'gridLineWidth',
      labelKey: 'style.gridLineWidth',
      type: 'slider',
      defaultValue: 1,
      min: 0,
      max: 5,
      step: 1,
      tab: 'style',
      group: 'grid',
      order: 5,
    },
    {
      id: 'gridLineColor',
      labelKey: 'style.gridLineColor',
      type: 'color',
      defaultValue: 'hsl(var(--border))',
      tab: 'style',
      group: 'grid',
      order: 6,
    },
    ...commonLegendOptions,
    ...commonTooltipOptions,
    ...commonNumberFormatOptions,
    {
      id: 'paletteName',
      labelKey: 'style.palette',
      type: 'select',
      defaultValue: 'zinc',
      options: [
        { value: 'zinc', labelKey: 'style.paletteZinc' },
        { value: 'slate', labelKey: 'style.paletteSlate' },
        { value: 'tableau10', labelKey: 'style.paletteTableau10' },
        { value: 'vibrant', labelKey: 'style.paletteVibrant' },
        { value: 'pastel', labelKey: 'style.palettePastel' },
      ],
      tab: 'style',
      group: 'colors',
      order: 13,
    },
  ],

  minRequirements: {
    measures: 1,
  },
}
