import { Icons } from '@/config/icons'
import { commonNumberFormatOptions } from './commonNumberFormat'
import { commonTooltipOptions } from './commonTooltip'
import type { ChartConfig } from './types'

export const sankeyChartConfig: ChartConfig = {
  type: 'sankey',
  nameKey: 'charts.sankey.name',
  icon: Icons.chartSankey,
  category: 'flow',
  descriptionKey: 'charts.sankey.description',
  supportsOrientation: false,
  supportsStacking: false,

  channels: [
    {
      id: 'source',
      labelKey: 'channels.source',
      placeholderKey: 'channels.sourcePlaceholder',
      accepts: 'dimension',
      cardinality: 'single',
      required: true,
      icon: Icons.Dimensions,
      order: 1,
      tab: 'config',
      group: 'flow',
    },
    {
      id: 'target',
      labelKey: 'channels.target',
      placeholderKey: 'channels.targetPlaceholder',
      accepts: 'dimension',
      cardinality: 'single',
      required: true,
      icon: Icons.Dimensions,
      order: 2,
      tab: 'config',
      group: 'flow',
    },
    {
      id: 'value',
      labelKey: 'channels.value',
      placeholderKey: 'channels.valuePlaceholder',
      accepts: 'measure',
      cardinality: 'single',
      required: true,
      defaultAggregation: 'sum',
      icon: Icons.Measures,
      order: 3,
      tab: 'config',
      group: 'data',
    },
  ],

  styleOptions: [
    {
      id: 'nodeAlign',
      labelKey: 'style.nodeAlign',
      type: 'select',
      defaultValue: 'justify',
      options: [
        { value: 'justify', labelKey: 'style.nodeAlignJustify' },
        { value: 'left', labelKey: 'style.nodeAlignLeft' },
        { value: 'right', labelKey: 'style.nodeAlignRight' },
      ],
      tab: 'style',
      group: 'layout',
      order: 1,
    },
    {
      id: 'nodeWidth',
      labelKey: 'style.nodeWidth',
      type: 'slider',
      defaultValue: 20,
      min: 10,
      max: 40,
      step: 2,
      tab: 'style',
      group: 'appearance',
      order: 2,
    },
    {
      id: 'nodeGap',
      labelKey: 'style.nodeGap',
      type: 'slider',
      defaultValue: 8,
      min: 2,
      max: 20,
      step: 2,
      tab: 'style',
      group: 'appearance',
      order: 3,
    },
    {
      id: 'curveness',
      labelKey: 'style.curveness',
      type: 'slider',
      defaultValue: 0.5,
      min: 0,
      max: 1,
      step: 0.1,
      tab: 'style',
      group: 'appearance',
      order: 4,
    },
    ...commonTooltipOptions,
    ...commonNumberFormatOptions,
  ],

  minRequirements: {
    dimensions: 2,
    measures: 1,
  },
}
