import { Icons } from '@/config/icons'
import { commonAxisOptions } from './commonAxis'
import { commonLegendOptions } from './commonLegend'
import { commonNumberFormatOptions } from './commonNumberFormat'
import { commonTooltipOptions } from './commonTooltip'
import type { ChartConfig } from './types'

export const scatterChartConfig: ChartConfig = {
  type: 'scatter',
  nameKey: 'charts.scatter.name',
  icon: Icons.chartScatter,
  category: 'relationship',
  descriptionKey: 'charts.scatter.description',
  supportsOrientation: false,
  supportsStacking: false,
  channels: [
    {
      id: 'x',
      labelKey: 'channels.columns',
      placeholderKey: 'channels.xAxis.scatterPlaceholder',
      accepts: 'measure',
      cardinality: 'single',
      required: true,
      allowAggregation: false,
      descriptionKey: 'channels.xAxis.scatterDescription',
      icon: Icons.Measures,
      order: 1,
      tab: 'config',
      group: 'axes',
    },
    {
      id: 'y',
      labelKey: 'channels.rows',
      placeholderKey: 'channels.yAxis.scatterPlaceholder',
      accepts: 'measure',
      cardinality: 'single',
      required: true,
      allowAggregation: false,
      descriptionKey: 'channels.yAxis.scatterDescription',
      icon: Icons.Measures,
      order: 2,
      tab: 'config',
      group: 'axes',
    },
    {
      id: 'color',
      labelKey: 'channels.breakdown',
      placeholderKey: 'channels.breakdownPlaceholder',
      accepts: 'dimension',
      cardinality: 'optional',
      required: false,
      descriptionKey: 'channels.color.scatterDescription',
      icon: Icons.Dimensions,
      order: 3,
      tab: 'config',
      group: 'encoding',
    },
  ],
  styleOptions: [
    {
      id: 'pointSize',
      labelKey: 'style.pointSize',
      type: 'slider',
      defaultValue: 10,
      min: 4,
      max: 30,
      step: 2,
      tab: 'style',
      group: 'appearance',
      order: 1,
    },
    {
      id: 'opacity',
      labelKey: 'style.opacity',
      type: 'slider',
      defaultValue: 0.7,
      min: 0.1,
      max: 1,
      step: 0.1,
      tab: 'style',
      group: 'appearance',
      order: 2,
    },
    {
      id: 'showTrendline',
      labelKey: 'style.showTrendline',
      type: 'toggle',
      defaultValue: false,
      tab: 'style',
      group: 'trendline',
      order: 3,
    },
    {
      id: 'trendlineWidth',
      labelKey: 'style.lineWidth',
      type: 'slider',
      defaultValue: 2,
      min: 1,
      max: 8,
      step: 0.5,
      tab: 'style',
      group: 'trendline',
      order: 4,
    },
    {
      id: 'trendlineColor',
      labelKey: 'style.trendlineColor',
      type: 'color',
      defaultValue: 'hsl(var(--foreground))',
      tab: 'style',
      group: 'trendline',
      order: 5,
    },
    {
      id: 'showGrid',
      labelKey: 'style.showGrid',
      type: 'toggle',
      defaultValue: true,
      tab: 'style',
      group: 'grid',
      order: 6,
    },
    {
      id: 'gridLineWidth',
      labelKey: 'style.gridLineWidth',
      type: 'slider',
      defaultValue: 1,
      min: 0,
      max: 5,
      step: 1,
      tab: 'style',
      group: 'grid',
      order: 7,
    },
    {
      id: 'gridLineColor',
      labelKey: 'style.gridLineColor',
      type: 'color',
      defaultValue: 'hsl(var(--border))',
      tab: 'style',
      group: 'grid',
      order: 8,
    },
    ...commonLegendOptions,
    ...commonAxisOptions,
    ...commonTooltipOptions,
    ...commonNumberFormatOptions,
    {
      id: 'paletteName',
      labelKey: 'style.palette',
      type: 'select',
      defaultValue: 'zinc',
      options: [
        { value: 'zinc', labelKey: 'style.paletteZinc' },
        { value: 'slate', labelKey: 'style.paletteSlate' },
        { value: 'tableau10', labelKey: 'style.paletteTableau10' },
        { value: 'vibrant', labelKey: 'style.paletteVibrant' },
        { value: 'pastel', labelKey: 'style.palettePastel' },
      ],
      tab: 'style',
      group: 'colors',
      order: 13,
    },
  ],
  minRequirements: {
    measures: 2,
  },
}
